version: '2'
services:
    postgres:
        image: postgres:9.6.1
        env_file:
            - ./common.env
        environment:
            - POSTGRES_PASSWORD=root
        ports:
            - "5432:5432"
    api:
        environment:
            - OIDC_DB_ADAPTER=postgresql
            - OIDC_DB_USER=postgres
            - OIDC_DB_PASSWORD=root
            - OIDC_DB_NAME=postgres
            - OIDC_DB_HOST=postgres
            - OIDC_DB_PORT=5432
        depends_on:
            - postgres
            - redis
        entrypoint: ./wait-for-it.sh -t 0 postgres:5432 --
